version: "3.0"

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - go-multy-srv-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  go-multy-srv-db: